---
###
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  labels:
#    k8s-app: kubernetes-dashboard
#  name: kubernetes-dashboard
#  namespace: kubernetes-dashboard

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: admin
  namespace: kubernetes-dashboard

---

#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  labels:
#    k8s-app: kubernetes-dashboard
#  name: kubernetes-dashboard
#  namespace: kubernetes-dashboard
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: kubernetes-dashboard
#subjects:
#  - kind: ServiceAccount
#    name: kubernetes-dashboard
#    namespace: kubernetes-dashboard




apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole   #changed
  name: cluster-admin  #fixed
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: kubernetes-dashboard
